FROM golang:1.22 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/nobus-csi ./cmd/nobus-csi

FROM debian:12-slim
RUN apt-get update \
  && apt-get install -y --no-install-recommends e2fsprogs xfsprogs util-linux blkid ca-certificates \
  && rm -rf /var/lib/apt/lists/*
COPY --from=build /out/nobus-csi /nobus-csi
ENTRYPOINT ["/nobus-csi"]
