FROM golang:1.22 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/nobus-csi ./cmd/nobus-csi

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/nobus-csi /nobus-csi
ENTRYPOINT ["/nobus-csi"]
