{{- if not .Values.nobus.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nobus-csi.secretName" . }}
  namespace: {{ include "nobus-csi.namespace" . }}
  labels:
    {{- include "nobus-csi.labels" . | nindent 4 }}
type: Opaque
stringData:
  NOBUS_API_URL: {{ required "nobus.apiUrl is required" .Values.nobus.apiUrl | quote }}
  NOBUS_PROJECT_ID: {{ required "nobus.projectId is required" .Values.nobus.projectId | quote }}
  NOBUS_AVAILABILITY_ZONE: {{ required "nobus.availabilityZone is required" .Values.nobus.availabilityZone | quote }}
  {{- if .Values.nobus.volumeType }}
  NOBUS_VOLUME_TYPE: {{ .Values.nobus.volumeType | quote }}
  {{- end }}
  {{- if .Values.nobus.token }}
  NOBUS_TOKEN: {{ .Values.nobus.token | quote }}
  {{- end }}
  {{- if .Values.nobus.email }}
  NOBUS_EMAIL: {{ .Values.nobus.email | quote }}
  {{- end }}
  {{- if .Values.nobus.password }}
  NOBUS_PASSWORD: {{ .Values.nobus.password | quote }}
  {{- end }}
{{- end }}
